### ISSUE TITLE
Consider adding Or.of(Expression e)

### ISSUE THREAD

**Issue by BrynCooke** [bpodgursky/jbool_expressions#10]
The equivalent exists for [And](https://github.com/bpodgursky/jbool_expressions/blob/master/src/main/java/com/bpodgursky/jbool_expressions/And.java#L38) already

**Comment by bpodgursky** [comment]
sure: https://github.com/bpodgursky/jbool_expressions/commit/d0b5cead12819ddb23c2e87ae5183126d524899e

**Comment by BrynCooke** [comment]
Many thanks!

**Comment by BrynCooke** [comment]
Just out of interest is there planned to be another release of jbool_expressions? The reason I ask is that the library seems pretty much feature complete. If there isn't going to be another major release would it be possible to push this to maven central?

**Comment by bpodgursky** [comment]
just released 1.9.  should show up in maven central sometime later today.

**Comment by BrynCooke** [comment]
Great thanks again.
