### ISSUE TITLE
product-of-sums problem

### ISSUE THREAD

**Issue by leobuettiker** [bpodgursky/jbool_expressions#12]
Thanks for this cool library!

I found a little issue which does not behave like I would expect. When I build a product-of-sums from `A & (!A | !C | !D | !E | !F)` I would expect the outcome to be `(!C | !D | !E | !F) & A)` however the outcome is `((!C & A) | (!D & A) | (!E & A) | (!F & A))` which is equivalent to the first expression but to my knowledge not in the product-of-sums/CNF form.

Calculation of the therm in [wolfram alpha](http://www.wolframalpha.com/input/?i=CNF+a+and+(not+a+or+not+c+or+not+d+or+not+e)).

The unit test would be: 
`assertToPos("((!C | !D | !E | !F) & A)","A & (!A | !C | !D | !E | !F)");`

**Comment by bpodgursky** [comment]
Well... that was fun.  I think https://github.com/bpodgursky/jbool_expressions/commit/6e11b434dd3a2a3742fcc15d9e1de3a35cba43db fixes this case.  I'm not sure whether it fixes it 100% of the time, so let me see if you see it again.  Think it got introduced about a year ago when I added some simplifying (https://github.com/bpodgursky/jbool_expressions/commit/63a5a73712dd92eefe6a0af999fe69219a9145db)

Let me know if this looks good, and I can do a release if you need it.

**Comment by leobuettiker** [comment]
Thanks a lot for your fast response! It seems to work for me now.

**Comment by bpodgursky** [comment]
Great to hear.  Going to close this, let me know if you see problems.
