### ISSUE TITLE
Seemingly endless conversion to CNF

### ISSUE THREAD

**Issue by trueg** [bpodgursky/jbool_expressions#13]
When trying to convert the following expression to CNF via RuleSet.toCnf(), the latter seems to run forever. Sure, it is a rather big expression, but I had hoped that your (very nice) lib could handle it.

    (!S-950 | !S-P34 | (!S-001A & !S-002A & !S-003A & !S-004A & !S-005A & !S-006A & !S-007A & !S-008A & !S-009A & !S-011A & !S-012A & !S-015A & !S-017A & !S-018A & !S-019A & !S-021A & !S-022A & !S-026A & !S-027A & !S-028A & !S-031A & !S-032A & !S-036A & !S-037A & !S-038A & !S-039A & !S-041A & !S-042A & !S-045A & !S-048A & !S-051A & !S-052A & !S-055A & !S-057A & !S-058A & !S-061A & !S-062A & !S-065A & !S-068A & !S-069A & !S-071A & !S-072A & !S-073A & !S-077A & !S-078A & !S-081A & !S-082A & !S-085A & !S-088A & !S-091A & !S-092A & !S-095A & !S-098A & !S-101A & !S-102A & !S-104A & !S-105A & !S-108A & !S-111A & !S-112A & !S-114A & !S-115A & !S-118A & !S-121A & !S-124A & !S-125A & !S-128A & !S-131A & !S-132A & !S-135A & !S-138A & !S-141A & !S-142A & !S-144A & !S-145A & !S-148A & !S-151A & !S-152A & !S-154A & !S-155A & !S-157A & !S-158A & !S-161A & !S-164A & !S-165A & !S-168A & !S-171A & !S-175A & !S-178A & !S-189A & !S-191A & !S-192A & !S-196A & !S-197A & !S-198A & !S-199A & !S-201A & !S-202A & !S-204A & !S-205A & !S-206A & !S-207A & !S-208A & !S-211A & !S-212A & !S-214A & !S-215A & !S-217A & !S-218A & !S-219A & !S-221A & !S-222A & !S-224A & !S-225A & !S-227A & !S-228A & !S-231A & !S-232A & !S-234A & !S-235A & !S-237A & !S-238A & !S-239A & !S-241A & !S-242A & !S-244A & !S-245A & !S-246A & !S-247A & !S-248A & !S-251A & !S-252A & !S-254A & !S-255A & !S-257A & !S-258A & !S-261A & !S-262A & !S-263A & !S-264A & !S-265A & !S-267A & !S-268A & !S-269A & !S-271A & !S-272A & !S-274A & !S-275A & !S-277A & !S-278A & !S-281A & !S-282A & !S-284A & !S-285A & !S-287A & !S-288A & !S-291A & !S-292A & !S-294A & !S-295A & !S-296A & !S-297A & !S-298A & !S-299A & !S-301A & !S-305A & !S-308A & !S-311A & !S-314A & !S-315A & !S-318A & !S-321A & !S-325A & !S-328A & !S-331A & !S-332A & !S-335A & !S-338A & !S-341A & !S-348A & !S-351A & !S-358A & !S-361A & !S-363A & !S-368A & !S-371A & !S-378A & !S-381A & !S-382A & !S-386A & !S-387A & !S-388A & !S-391A & !S-392A & !S-395A & !S-398A & !S-401A & !S-402A & !S-404A & !S-405A & !S-406A & !S-407A & !S-408A & !S-409A & !S-411A & !S-412A & !S-414A & !S-415A & !S-418A & !S-421A & !S-425A & !S-428A & !S-431A & !S-432A & !S-435A & !S-438A & !S-441A & !S-442A & !S-445A & !S-447A & !S-448A & !S-451A & !S-452A & !S-455A & !S-457A & !S-458A & !S-461A & !S-471A & !S-472A & !S-475A & !S-476A & !S-477A & !S-478A & !S-481A & !S-482A & !S-485A & !S-487A & !S-488A & !S-491A & !S-492A & !S-495A & !S-498A & !S-501A & !S-502A & !S-504A & !S-515A & !S-517A & !S-519A & !S-521A & !S-524A & !S-527A & !S-528A & !S-531A & !S-532A & !S-534A & !S-535A & !S-536A & !S-537A & !S-538A & !S-541A & !S-542A & !S-548A & !S-551A & !S-552A & !S-554A & !S-555A & !S-557A & !S-558A & !S-561A & !S-564A & !S-565A & !S-567A & !S-568A & !S-571A & !S-572A & !S-574A & !S-575A & !S-577A & !S-578A & !S-581A & !S-582A & !S-584A & !S-585A & !S-586A & !S-587A & !S-588A & !S-591A & !S-594A & !S-595A & !S-598A & !S-601A & !S-604A & !S-605A & !S-608A & !S-611A & !S-614A & !S-615A & !S-618A & !S-621A & !S-625A & !S-628A & !S-631A & !S-637A & !S-638A & !S-641A & !S-648A & !S-651A & !S-654A & !S-661A & !S-665A & !S-671A & !S-678A & !S-681A & !S-691A & !S-698A & !S-701A & !S-702A & !S-704A & !S-705A & !S-707A & !S-708A & !S-711A & !S-718A & !S-721A & !S-725A & !S-726A & !S-727A & !S-728A & !S-731A & !S-732A & !S-735A & !S-738A & !S-741A & !S-742A & !S-746A & !S-747A & !S-748A & !S-751A & !S-752A & !S-755A & !S-756A & !S-761A & !S-767A & !S-771A & !S-778A & !S-781A & !S-782A & !S-786A & !S-787A & !S-798A & !S-801A & !S-802A & !S-804A & !S-805A & !S-807A & !S-808A & !S-811A & !S-812A & !S-814A & !S-815A & !S-817A & !S-818A & !S-821A & !S-822A & !S-824A & !S-825A & !S-827A & !S-828A & !S-831A & !S-832A & !S-834A & !S-835A & !S-838A & !S-841A & !S-842A & !S-843A & !S-844A & !S-845A & !S-848A & !S-851A & !S-852A & !S-854A & !S-855A & !S-857A & !S-858A & !S-861A & !S-864A & !S-865A & !S-867A & !S-868A & !S-871A & !S-872A & !S-873A & !S-874A & !S-875A & !S-877A & !S-878A & !S-881A & !S-884A & !S-885A & !S-887A & !S-888A & !S-895A & !S-897A & !S-901A & !S-904A & !S-905A & !S-908A & !S-911A & !S-914A & !S-915A & !S-918A & !S-921A & !S-951A & !S-954A & !S-955A & !S-958A & !S-961A & !S-962A & !S-965A & !S-968A & !S-971A & !S-974A & !S-975A & !S-977A & !S-978A & !S-984A & !S-985A & !S-987A & !S-991A & !S-992A & !S-994A & !S-995A & !S-996A & !S-997A & !S-998A & !S-999A & !S-X07A & !S-X09A) | (S-501A & S-X06) | (S-501A & S-X10) | (S-501A & S-X12) | (S-501A & S-X17) | (S-501A & S-X30) | (S-501A & S-X35) | (S-501A & S-X39) | (S-501A & S-X46) | (S-521A & S-956) | S-505A | S-507A | S-508A | S-511A | S-514A | S-518A | S-525A | S-545A | S-964A | S-967A)

I will run the conversion over night to see if it finishes at all but maybe you can already replicate it and see what the problem is.

Thanks a lot for the lib and looking into this issue.

**Comment by bpodgursky** [comment]
This takes ~30 seconds on my laptop and produces an expression with 30667 terms.   Maybe you should give it more heap, if it's hitting GC?  Honestly it doesn't shock me that it's so slow with an expression this large.  What code exactly are you running?

**Comment by ostauss** [comment]
Hello,
i tried to convert the following formula to DNF. 
After 19h i stoped the java task without success... 

(( a | b | c | d | e | f ) & ( g & h & ( i | j | k ) & !( l | m | n ))) | ( m | n )

Any idea? Endless loop or bad hardware?

**Comment by bpodgursky** [comment]
The problem with only touching this library every 3 months is that I have no memory of why I wrote some of the code...

This change seems to produce output in a reasonable time: https://github.com/bpodgursky/jbool_expressions/commit/cf7a347bf5bc365d8b955123a7bf4259ec838f3f.  

The output is too long to check by hand, but seems reasonable, and the change doesn't break other tests - does it look ok to you @ostauss?  I'll do a release if so.

**Comment by ostauss** [comment]
Hi, 
looks good for me 👍 

I did also some tests with the expression and found that the "CollapseNegation" consumes most of the time.... (seems close to your changes)

By the way -- a really nice software with an elegant architecture!!

**Comment by bpodgursky** [comment]
Great, thanks!  The latest release 1.11 includes this change.
