### ISSUE TITLE
Version 1.10 not yet on maven central

### ISSUE THREAD

**Issue by leobuettiker** [bpodgursky/jbool_expressions#14]
The documentation shows that you can include the library from maven central:
`<dependency>
    <groupId>com.bpodgursky</groupId>
    <artifactId>jbool_expressions</artifactId>
    <version>1.10</version>
</dependency>`

However on [maven central](https://mvnrepository.com/artifact/com.bpodgursky/jbool_expressions) version 1.10 is not yet published.

Thanks a lot for your work!

**Comment by bhchandra** [comment]
Yes, version 1.10 is not yet in maven central.

**Comment by bpodgursky** [comment]
Indeed, I forgot to actually release the bundle on Sonatype.  Should show up soon -- please re-open if it doesn't.

**Comment by bpodgursky** [comment]
Try now: http://repo1.maven.org/maven2/com/bpodgursky/jbool_expressions/1.10/.  sorry about that, thanks for pointing it out.

**Comment by bhchandra** [comment]
Thank you for the library.
