### ISSUE TITLE
Standardlise hashCode and equals for performance

### ISSUE THREAD

**Issue by BrynCooke** [bpodgursky/jbool_expressions#15]
Hi,
I have been a user of jbool_expressions for a while and have found it very good.

I was wondering if you would consider a pull request to implement hashCode and equals using standard java patterns rather than using string manipulation? 

The reason for this is that I noticed during profiling that all this string manipulation shows up as a hot method.

The changes are pretty simple:

1. remove hashCode and equals from Expression.
2. change Expression#compareTo to compare via hashCode rather than string.
3. implement hashCode and Equals in subclasses of Expression.

The downside of this is that this is a breaking change. Users with custom Expressions will have to implement hashCode and equals on all their subclasses of Expression.

The upside is that string manipulation is eliminated and implementing hashCode and equals can be optimised on a class by class basis.

**Comment by bpodgursky** [comment]
Interesting, I have never done any real profiling on this library.  I think (1) and (3) tentatively sound fine (would need to see code).  (2) sounds dangerous though for a standard int hashcode -- one collision every couple billion tests seems like it would introduce a correctness bug.

I'm not worried about making breaking changes.  I doubt anyone has added complicated new Expressions.  Happy to review any PRs that are up.

**Comment by BrynCooke** [comment]
I see your point about 2. I've added some logic to deal with collisions. It's not ideal, but the chances of collision are pretty small, so mostly the happy path will be quick.

One thing I did not look in to closely was if lexographic sorting is required for expression simplification. The test results seem to indicate that things are working (even if they are in different order).
