### ISSUE TITLE
Expression parser doesn't create exactly the expression being parsed

### ISSUE THREAD

**Issue by BrynCooke** [bpodgursky/jbool_expressions#20]
I had been doing some experimentation with optimising SimplifyNExprChildren but realised that my tests were not behaving as expected. It turned out that the expression parser was not creating exactly the same tree as was being passed in.

I'd like to modify the expression parser to honour the general structure of expressions.
This means that in the expression parser tests the calls to simplify the parsed expression can be dropped.

**Comment by bpodgursky** [comment]
Do you have an example?

**Comment by BrynCooke** [comment]
(A | B | C) is parsed as (A | (B | C))

**Comment by bpodgursky** [comment]
Great, thanks.  I'm out for a day or two, but I will take a look at these PRs over the weekend.

**Comment by bpodgursky** [comment]
@BrynCooke I've merged both these PRs in.  Going to do a release as well.  Good catch, thanks!
