### ISSUE TITLE
Errors when cloning.

### ISSUE THREAD

**Issue by jrgensol** [bpodgursky/jbool_expressions#24]
I forked your project and cloned it to my computer. Then I added all the dependencies into builpath.

And in /src/main/java/com/bpodgursky/jbool_expressions/parsers/ExprParser.java eclipse is complaining about how BooleanExprLexer and BooleanExprParser can't be resolved to a type.

this happens on lines 32, 35, 36, 47, 52, 61, 66, 74, 76, 78, 80, 82 and 85. 

Any idea how I can fix it?

**Comment by bpodgursky** [comment]
Those are generated by the antlr maven plugin: https://github.com/bpodgursky/jbool_expressions/blob/master/pom.xml#L145

If you are just trying to consume this as a library, I recommend using the published artifact via Maven or Gradle.  

If you are trying to make changes locally, you can generate the parser and lexer locally with "mvn compile" in the project root.

**Comment by jrgensol** [comment]
I already have gotten it to work as a library. I have now idea what you meant with '"mvn compile" in the project root'

I was planning to add the ability to replace a Variable with an Expression similarly to how the assign function works so that I could pre-build some Expression, and the expand it with other sub Expressions.

And a function that returns a set of all K represented in an Expression.

I already have made these in my code, but wanted to put it in the library to make it look a bit cleaner, and to give something back in return for getting to use this amazing library in the first place.

**Comment by bpodgursky** [comment]
Maven (https://maven.apache.org/) is the build tool this project uses.  If you have Maven on your path, the "mvn" command is how you invoke the build tool -- you would just run "mvn compile" in the directory where you have checked out the project.  One of the initial stages of the build will generate the files you see as missing.  The reason these files aren't checked in is because they are automatically generated from the grammar files.

Let me know if it is still unclear.  Happy to review any PRs once you get it working.

**Comment by jrgensol** [comment]
Ok, after messing around with installing maven and playing with environmental variables i finally got to run "mvn compile" without any errors.

But just to be clear, eclipse is still supposed to complain about errors in the source code?

**Comment by bpodgursky** [comment]
The generated source will be in target/generated-sources.  You should be able to add that as a source directory in Eclipse to get rid of the compile errors (I haven't used eclipse in a while so I'm not sure if it would pick up the directory if you imported the project from the pom.xml)

**Comment by jrgensol** [comment]
Thanks, I found the target folder, and Eclipse aren't complaining about any errors there. I didn't import the project from the pom.xml. I used the github application and the big green button on the website that says "clone or download"

Just want to make sure I got this. I need to make any modifications to the src folder for git to be able to see the changes. Then for testing I need to run "mvn compile" in the root folder, then export the contents of the target folder to a jar file before I can use it in other projects.

**Comment by bpodgursky** [comment]
"mvn package" will generate a jar in target/ which you can use in other projects.  You shouldn't need to package anything manually.

If the other projects use maven or gradle, you could alternately update pom.xml with a new version (1.15-TEST"), mvn install, and update the dependency in your other project.

**Comment by jrgensol** [comment]
I've never used either maven or gradle before, and haven't used github for anything other than to find libraries in the last 3 years.

To be able to upload my changes to github I need to change the files in src, not the stuff generated by maven. Right?

**Comment by bpodgursky** [comment]
Yep.  The stuff in target/ is all autogenerated based on the code in src/.  It isn't checked into git.

**Comment by jrgensol** [comment]
Thanks, sorry for needing so much help, hopefully you can expect a pull request in the next few days.

**Comment by bpodgursky** [comment]
No problem.  Look forward to it.
