### ISSUE TITLE
Assumptions about RuleSet.simplify

### ISSUE THREAD

**Issue by jrgensol** [bpodgursky/jbool_expressions#28]
Assuming no unknown bugs, can I make three assumptions about the following code?
`e=RuleSet.simplify(e);`

1. Because of literal removal, either e is a literal or e does not contain any literals.

2. Because of negation simplification and De Morgans law, all instances of Not will only contain Variables, and no other extensions of Expression (like And/Or/Not).

3. Because of And / Or de-duplication and flattening. All children of an And will be either Or, Not or Variable, likewise all children of an Or will be either And, Not or Variable. Although there can be more nested downwards.

**Comment by bpodgursky** [comment]
I don't think (2) and (3) are true for RuleSet.simplify.  I would expect it for the output of RuleSet.toDNF though.

**Comment by jrgensol** [comment]
Sadly converting to DNF runs the risk of growing exponentially.
Would it be possible to request RuleSet.toNNF as a new feature? That would take care of (2).

**Comment by bpodgursky** [comment]
I don't think necessarily needs to be in RuleSet; you can simplify using a custom rule set, ex:

````

  protected static <K> List<Rule<?, K>> customRules() {

    //  from RulesHelper.simplifyRules
    List<Rule<?, K>> rules = new ArrayList<>();
    rules.add(new SimplifyAnd<K>());
    rules.add(new SimplifyOr<K>());
    rules.add(new SimplifyNot<K>());
    rules.add(new CombineAnd<K>());
    rules.add(new CombineOr<K>());
    rules.add(new SimplifyNExpression<K>());
    rules.add(new SimplifyNExprChildren<K>());
    rules.add(new CollapseNegation<K>());

    //  add demorgan's rule
    rules.add(new DeMorgan<K>());

    return rules;
  }

  public void testMyMethod(){

    System.out.println(RulesHelper.applySet(
        ExprParser.parse("!(A & C)"),
        customRules()
    ));

  }
````
if other people find this useful I'm not against adding it, but I'm inclined to keep that interface simple until then.

**Comment by jrgensol** [comment]
Looking through RulesHelper I see that the protected function demorganRules already does that. Is there a reason it is protected, or could it be made public?

**Comment by bpodgursky** [comment]
No, no good reason.  I just pushed a change to make them public.
