### ISSUE TITLE
What is your release schedule?

### ISSUE THREAD

**Issue by babineaum** [bpodgursky/jbool_expressions#32]
Good day!

A colleauge of mine just merged something to master here. We would like to have a maven artifact built for this latest merge. Is it possible to get a release cut? Or do you have a specific release cadence? Thanks

**Comment by bpodgursky** [comment]
There is no schedule, it's whenever someone needs it.  I can do it today.

**Comment by bpodgursky** [comment]
1.16 is released.  Let me know if there are any issues.

**Comment by mgurmendez** [comment]
Thank you @bpodgursky!!!
