### ISSUE TITLE
Expression#sort should be public.

### ISSUE THREAD

**Issue by BrynCooke** [bpodgursky/jbool_expressions#39]
I'm trying to make something similar to the Not expression class. However as sort is `protected` I can't implement sort in the same way. As `Not` is in the same package as `Expression` it works for the inbuilt class.

I think Expression#sort should probably be public.

**Comment by bpodgursky** [comment]
Done https://github.com/bpodgursky/jbool_expressions/commit/377b587f771470dfc3df2e69c6ff49f5f45cc1f2

Do you need a release?

**Comment by BrynCooke** [comment]
That'd be really helpful. Thanks!

**Comment by bpodgursky** [comment]
Released, give it a few hours.
