### ISSUE TITLE
Simplification issue (not error)

### ISSUE THREAD

**Issue by peplamb** [bpodgursky/jbool_expressions#5]
I have the following expression,

    A&!(B|!C)

when simplified I am expecting the result to be

    A&!B&C

But the output of this library is,

    (!(!C|B)&A)

Any help is appreciated! Thank you!

**Comment by peplamb** [comment]
found the answer using,

        private String simplify(String expression) {
            List<Rule<?, String>> rules = Lists.newArrayList();
            rules.add(new DeMorgan<String>());
            rules.add(new SimplifyAnd<String>());
            rules.add(new SimplifyOr<String>());
            rules.add(new SimplifyNot<String>());
            rules.add(new CombineAnd<String>());
            rules.add(new CombineOr<String>());
            rules.add(new SimplifyNExpression<String>());
            rules.add(new SimplifyNExprChildren<String>());
            Expression<String> parsedExpression = RuleSet.applySet(ExprParser.parse(expression), rules);
            return parsedExpression.toString();
        }

**Comment by bpodgursky** [comment]
Hey, sorry I haven't had a chance to look at this yet.  So the second set of rules did simplify it down to what you expected?  I'm going to try to look at this tonight.

**Comment by peplamb** [comment]
yes it translated `A & !(B | !C)` to `(!B & C & A)` thank you @bpodgursky bpodgur
