### ISSUE TITLE
ClassCastException when transforming to DNF Expression with RuleSet.toDNFViaQMC

### ISSUE THREAD

**Issue by newalderaan** [bpodgursky/jbool_expressions#51]
Hi,

With version 1.23 of the library and Expressions like these where there isn't any Variable inside of the Logical Expression:

- And.of(Literal.getTrue)
- Or.of(Literal.getTrue)
- Or.of(And.of(Literal.getTrue))
- And.of(Literal.getTrue, .., Literal.getTrue)
- Or.of(Literal.getTrue, .., Literal.getTrue)

And doing this call:

RuleSet.toDNFViaQMC(expression, ExprOptions.noCaching())

This Exception is thrown:

`Exception in thread "main" java.lang.ClassCastException: com.bpodgursky.jbool_expressions.And cannot be cast to com.bpodgursky.jbool_expressions.LiteralException in thread "main" java.lang.ClassCastException: com.bpodgursky.jbool_expressions.And cannot be cast to com.bpodgursky.jbool_expressions.Literal at com.bpodgursky.jbool_expressions.rules.QuineMcCluskey.findMinterms(QuineMcCluskey.java:412) at com.bpodgursky.jbool_expressions.rules.QuineMcCluskey.findMinterms(QuineMcCluskey.java:399) at com.bpodgursky.jbool_expressions.rules.QuineMcCluskey.toDNF(QuineMcCluskey.java:75) at com.bpodgursky.jbool_expressions.rules.RuleSet.toDNFViaQMC(RuleSet.java:52)`

Thanks for having developed this library

**Comment by bpodgursky** [comment]
That's fun — thanks for the catch.  Does this seem like it'd handle everything you ran into? https://github.com/bpodgursky/jbool_expressions/pull/52/files

**Comment by zaza** [comment]
I ran all the expressions from @newalderaan comment with the latest version of the lib and there was no error. Looks like https://github.com/bpodgursky/jbool_expressions/pull/52 did the trick. @bpodgursky feel free to close this.

**Comment by bpodgursky** [comment]
Thanks!
